config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  
  get 'static_pages/index'

  resources :orders, only: [:new, :create]
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  devise_for :users
  get 'users/:id' => 'users#show'

  resources :items do
    post 'add_to_cart', on: :member
  end #cette configuration de route crée une route POST spécifique pour l'action add_to_cart qui peut être utilisée pour ajouter un article spécifique au panier. 

  resources :carts, only: [:create, :show, :update, :destroy]
  resources :cart_items, only: [:create, :update, :destroy]

  get 'contact', to: 'static_pages#contact'

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :items, through: :order_items
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
  end

  def create

  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/create.html.erb
<h2>Merci ! Nous confirmons votre paiement de  <strong>$5.00</strong>!</h2>

app/views/orders/new.html.erb
<center>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
<br>
<br>
  <%= form_tag orders_path do %>
    <article>
      <% if flash[:error].present? %>
        <div id="error_explanation">
          <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <label class="amount">
        <span>Amount: $5.00</span>
      </label>
    </article>
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-description="Achat d'un produit"
        data-amount="500"
        data-locale="fr">
    </script>
  <% end %>
</center>