config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  
  get 'static_pages/index'

  resources :orders, only: [:new, :create]
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  devise_for :users
  get 'users/:id' => 'users#show'

  resources :items do
    post 'add_to_cart', on: :member
  end #cette configuration de route crée une route POST spécifique pour l'action add_to_cart qui peut être utilisée pour ajouter un article spécifique au panier. 

  resources :carts, only: [:create, :show, :update, :destroy]
  resources :cart_items, only: [:create, :update, :destroy]

  get 'contact', to: 'static_pages#contact'

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/item.rb
class Item < ApplicationRecord
    has_many :order_items, dependent: :nullify
    has_many :cart_items, dependent: :nullify
    
    def image_filename
        
        self[:image_filename]
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy ]
  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy!

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def add_to_cart
    @item=Item.find(params[:id])
    current_user.add_item(@item)
    redirect_to items_path, notice: "Item ajouté au panier avec succès"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_cards.html.erb
<div class="container mx-auto grid max-w-2xl grid-cols-1 gap-x-1 gap-y-1 pt-3 mt-3 lg:mt-2 lg:pt-2 lg:mx-0 lg:max-w-none md::grid-cols-2 lg:grid-cols-3">
  <% @items.each do |item| %> 
    <article class="flex max-w-xl flex-col items-center justify-between">
      <div class="group relative">
        <div class="md:w-96 md:h-52 mb-1 justify-center overflow-hidden flex items-center inline-flex">
          <%= link_to(image_tag("#{item.image_url}", class: "w-full h-full object-cover", alt: "kitten hiding into a jean"), item_path(item.id)) %>
        </div>
      </div>
      <div class="relative flex items-center gap-x-4 mb-10">
        <div class="text-sm leading-6">
          <p class="font-semibold text-gray-900">
            <%= link_to(item.title, item_path(item.id)) %>
          </p>
          <p class="text-gray-600 text-center"><%= item.price %> euros</p>
        </div>
      </div>
    </article>
  <% end %>
</div>

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_hero.html.erb
<div class="m-5" >
  <div class="grid max-w-screen-xl px-4 py-8 mx-auto lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12">
    <div class="mr-auto place-self-center lg:col-span-7">
      <h1 class="max-w-xl mb-4 text-4xl font-bold tracking-tight leading-none md:text-5xl">Tout ce que vous pouvez imaginer, vous le trouverez sur Shutterstock</h1>
      <p class="max-w-xl mb-6 font-light text-gray-500 lg:mb-8 md:text-lg lg:text-xl white:text-gray-400">Vous trouverez ici tout ce dont vous avez besoin. Des contenus haut de gamme, des outils de création intuitifs et des innovations dans le domaine de l’IA, le tout à portée de clic.</p>
      <div class="border-gray-900 border-b max-w-max">
        <a href="#" class="inline-flex items-center justify-center py-3 mr-3 text-base font-medium text-center text-gray-900 rounded-lg bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 dark:focus:ring-primary-900">
          Découvrir notre collection
          <!--Flèche associée au bouton-->
          <svg class="w-5 h-5 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </a>
      </div>
    </div>
    <div class="hidden max-w-full lg:mt-5 lg:col-span-5 lg:flex">
      <%= image_tag("chaton_sur-dos2.jpeg", alt: "Little red kitten playing on its back")%>
    </div>                
  </div>
</div>

app/views/items/_item.html.erb
<div class="max-w-screen-xl mx-auto h-46 bg-white flex flex-col justify-start items-center mt-10 py-12 px-4 sm:px-6 lg:px-8">
  <div class="grid grid-cols-1 gap-8 sm:grid-cols-2">     
    <!-- ... Image du chat ... -->
    <img class="w-auto flex-col inline-flex ">
      <img class="">
        <%= link_to item_path(item.id) do %>
          <%= image_tag(item.image_url, class: "w-full h-full object-cover items-baseline", alt: "Description de l'image") %>
        <% end %>
      </img>
    </img>

    <!-- ... PARTIE DROITE ... -->
    <div class="flex flex-col justify-evenly mt-8">
      <!-- ...ITEMS/NAVCRUB ... -->
      <div class = "mb-6">
      <%= render 'items/navcrub' %>
      </div>
      <div class="h-3/4 flex-col">
      <!-- ... TITRE + DESCRIPTIONS ... -->              
      <h1 class = "font-bold text-xl"> <strong> <%= item.title %>  </strong></h1>
          <p><%= item.description%><p>
      </div>
      <div class="h-auto flex-col mt-10"> 
        <div class ="text-xl"> <strong> <%= item.price %>  € </strong></div>
      </div>          
      
      <!-- ...  INFO SUR UTILISATEUR ETC ... -->
      <div class=" py-6 border-t border-white border-opacity-0 flex-col ">
        <div class="mt-8">32 personnes ont achetées cette photo</div>
        <div class=" border-gray-200 flex flex-col justify-start gap-2 my-8  w-1/2 ">
          <div class="flex justify-start items-start sm:grid sm:grid-cols-2 gap-auto">
              <div class="text-zinc-500 text-xs font-normal font-['Inter'] leading-tight">By:</div>
              <div class="text-neutral-900 text-xs font-normal font-['Inter'] leading-tight ">@BlackPanter77</div>
          </div>

          <div class="flex justify-start items-start sm:grid sm:grid-cols-2 gap-auto">
              <div class="text-zinc-500 text-xs font-normal font-['Inter'] leading-tight">Nom du cat:</div>
              <div class="text-neutral-900 text-xs font-normal font-['Inter'] leading-tight">Martin Mystere</div>
          </div>

          <div class="flex justify-start items-start sm:grid sm:grid-cols-2 gap-auto">
              <div class="text-zinc-500 text-xs font-normal font-['Inter'] leading-tight text-start">TAGS:</div>
              <div class="text-neutral-900 text-xs font-normal font-['Inter'] leading-tight text-start ">poils longs, face, solo cat, promo</div>
          </div>
        </div>

        <!-- ... BOUTON ACHAT ... -->
        <div class="h-auto py-6 border-t border-gray-200 flex-col  ">
          <div class="self-stretch h-15 flex-col justify-start items-start flex ">
                            
            <!-- ... bouton stripe immediat ... -->
            <%= button_to "Achat immediat stripe", checkout_create_path(total: item.price, item_id: item.id),form_class: "contents", class: "flex w-5/6 justify-center rounded-mdtext-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700 text-white shadow-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600", data: {turbo: false} %>

            <!-- ... bouton stripe ... -->
            <%= button_to cart_items_path(item_id: item.id), method: :post,form_class: "contents", class: "flex w-5/6 justify-center rounded-mdtext-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700 text-white shadow-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" do %>
              <svg class="w-3.5 h-3.5 me-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 21">
                <path d="M15 12a1 1 0 0 0 .962-.726l2-7A1 1 0 0 0 17 3H3.77L3.175.745A1 1 0 0 0 2.208 0H1a1 1 0 0 0 0 2h.438l.6 2.255v.019l2 7 .746 2.986A3 3 0 1 0 9 17a2.966 2.966 0 0 0-.184-1h2.368c-.118.32-.18.659-.184 1a3 3 0 1 0 3-3H6.78l-.5-2H15Z"/>
              </svg>
              Ajouter au panier
              </button>
              <%= form_with(url: cart_items_path, method: :post, local: true) do |form| %>
              <%= form.hidden_field :item_id, value: item.id %>

              <!-- ... Champ de saisie de la quantité ... -->
              <div class="flex items-center">
                <%= label_tag :quantity, "Quantité", class: "mr-2" %>
                <%= form.number_field :quantity, class: "w-12 px-2 py-4 text-center border-0 rounded-md bg-gray-800 text-white md:text-center", placeholder: "1", value: 1 %>
              </div>
              <% end %>
            <% end %>
          </div>                
        </div>        
      </div>
    </div>
  </div>
</div>
<!-- ... Description ... -->
<div class="h-auto px-6 sm:px-10 md:px-16 lg:px-40 bg-white flex-col justify-start gap-2 flex">
  <div class="gap-8 ">
    <div class="w-full sm:w-auto pr-4 flex-col gap-6 sm:inline-flex">
      <p class = "font-bold text-lg border-gray-900 border-b max-w-max" >Description</p>
    </div>

    <div class="w-full sm:w-[80%] lg:w-[70%] text-gray-700 text-lg font-normal leading-[30px]" >
      <p><%= item.description%><p>
      
      <!-- ... INFO COMPLEMENTAIRES ... -->
      <div class="mb-8 flex-col gap-3 text-base mt-6">
        <div class = "font-bold border-gray-900 border-b max-w-max"> 
          Information 
        </div>
        <ul>
          <li> race : Main coon<li>
          <li> habitat : interieur<li>
          <li> sexe : Male<li>
          <li> localisation : France<li>
        <ul>
      </div>
    </div>
  </div>
</div>

app/views/items/_items.html.erb
<section class="py-10 font-poppins dark:bg-gray-800">
    <div class="max-w-6xl px-4 mx-auto">
        <div class="flex flex-wrap mb-24 -mx-4">
            <div class="w-full px-4 md:w-1/2 order-2 md:order-1">
                <!-- Image principale du produit (à adapter) -->
                <img class="object-contain w-full lg:h-full" src="https://helios-i.mashable.com/imagery/articles/05bWohHVcmI4wy8gnlR3oBo/hero-image.fill.size_1200x900.v1623363665.png" alt="Photo de chat mignon">
            </div>
            <div class="w-full px-4 md:w-1/2 order-1 md:order-2">
                <div class="lg:pr-20">
                    <div class="mb-6">
                        <h2 class="max-w-xl mt-6 mb-6 text-xl font-semibold leading-loose tracking-wide text-gray-700 md:text-2xl dark:text-gray-300">
                            Martin Mystere
                        </h2>
                        <div class="flex flex-wrap items-center mb-6">
                            <!-- Détails du produit (à adapter) -->
                            <ul class="flex mb-4 mr-2 lg:mb-0">
                                <!-- Icons ou détails spécifiques du produit (ex: rating) -->
                                <li>
                                    <a href="#">
                                        <!-- Icon -->
                                    </a>
                                </li>
                                <!-- ... Autres détails -->
                            </ul>
                            <!-- Lien vers le magasin ou d'autres informations -->
                            <a class="mb-4 text-xs underline hover:text-blue-600 dark:text-gray-400 dark:hover:text-gray-300 lg:mb-0" href="/">
                                Voir plus de photos de chats
                            </a>
                        </div>
                        <!-- Prix du produit -->
                        <p class="inline-block text-2xl font-semibold text-gray-700 dark:text-gray-400">
                            <span>$15.99</span>
                            <span class="ml-3 text-base font-normal text-gray-500 line-through dark:text-gray-400">$19.99</span>
                        </p>
                    </div>
              <!-- Informations sur le produit (à adapter) -->
              <div class="mb-6">
                <h2 class="mb-2 text-lg font-bold text-gray-700 dark:text-gray-400">Détails du produit :</h2>
                <!-- Spécifications du produit -->
                <div class="bg-gray-100 dark:bg-gray-700 rounded-xl">
                  <div class="p-3 lg:p-5">
                          <!-- Informations sur le produit (ex: taille, couleur) -->
                          <!-- ... -->
                      </div>
                <!-- Stock et détails de livraison -->
                <div class="py-6 mb-6 border-t border-b border-gray-200 dark:border-gray-700">
                    <span class="text-base text-gray-600 dark:text-gray-400">En stock</span>
                    <p class="mt-2 text-sm text-blue-500 dark:text-blue-200">Expédition depuis l'entrepôt local.
                        <span class="text-gray-600 dark:text-gray-400">
                            Livraison estimée en 2-5 jours.
                        </span>
                    </p>
                </div>
                <!-- Boutons pour ajouter au panier ou acheter -->
                <div class="mb-6">
                        <!-- Boutons pour la quantité et les actions -->
                        <!-- ... -->
                <a href="#" class="w-full px-4 py-3 text-center text-blue-600 bg-blue-100 border border-blue-600 dark:hover:bg-gray-900 dark:text-gray-400 dark:border-gray-700 hover:bg-blue-600 hover:text-gray-100 lg:w-1/2 rounded-xl">
                  Ajouter au panier
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/items/_navcrub.html.erb
<nav class="flex" aria-label="Breadcrumb">
  <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
    <li class="inline-flex items-center">
      <a href="/" class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-blue-600 dark:text-black dark:hover:text-gray-700">
        <svg class="w-3 h-3 me-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
          <path d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z"/>
        </svg>
        Home
      </a>
    </li>
    <li>
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <a href="#" class="ms-1 text-sm font-medium text-gray-700 hover:text-blue-600 md:ms-2 dark:text-black dark:hover:text-gray-700"><%= @item.title %></a>
      </div>
    </li>
  </ol>
</nav>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", @item %> |
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/index.html.erb
<!-- Banner -->
<div class="relative flex justify-center items-center">
  <%= image_tag("banner.png", class: "h-96 object-cover w-full", alt: "Little red kitten playing on its back") %>
  <div class="absolute max-w-7xl text-center w-full">
    <h2 class="text-3xl md:text-5xl font-bold">Instant Miaou :</h2>
    <h2 class="text-3xl md:text-5xl font-bold">Trouvez des Images de Chats à Acquérir</h2>
    <p class="pt-6 text-base max-w-2xl text-center m-auto">
      Il y en aura pour tous les goûts ! 
    </p>
  </div>
</div>

<!-- All card items -->
<div class="md:mx-20 md:mt-4">  
  <div class="bg-white py-12">
    <div class="isolate bg-white px-6 lg:px-8">
      <%= render "cards" %>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", items_path %>
</div>

app/views/items/show.html.erb
<!-- Banner -->
<div class="relative flex justify-center items-center">
  <%= image_tag("banner.png", class: "h-96 object-cover w-full", alt: "Little red kitten playing on its back") %>
  <div class="absolute max-w-7xl text-center w-full px-8 md:px-5 ">
    <h2 class="text-3xl md:text-5xl font-bold">Capturez l'instant félin :</h2>
    <h2 class="text-3xl md:text-5xl font-bold">Adoptez cette photo adorable dès maintenant!</h2>
    <p class="pt-6 text-base max-w-2xl text-center m-auto">
      Votre dose de câlin virtuel, disponible en un clic ! 
    </p>
  </div>
</div>

<%= render @item %>