config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  
  get 'static_pages/index'

  resources :orders, only: [:new, :create]
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

  devise_for :users
  get 'users/:id' => 'users#show'

  resources :items do
    post 'add_to_cart', on: :member
  end #cette configuration de route crée une route POST spécifique pour l'action add_to_cart qui peut être utilisée pour ajouter un article spécifique au panier. 

  resources :carts, only: [:create, :show, :update, :destroy]
  resources :cart_items, only: [:create, :update, :destroy]

  get 'contact', to: 'static_pages#contact'

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/layouts/_footer.html.erb
<footer class="bg-white rounded-lg m-4 sticky top-[100vh]">
    <div class="w-full max-w-screen-xl mx-auto p-4">
        <div class="sm:flex sm:items-center sm:justify-between text-center">
                <span class="self-center text-2xl font-semibold whitespace-nowrap">KittyKat</span>
            </a>
            <ul class="flex flex-wrap text-center mt-4 sm:mt-0 mb-6 text-sm font-medium text-gray-500 sm:mb-0">
                <li>
                    <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" class="hover:underline me-4 md:me-6">A propos</a>
                </li>
                <li>
                    <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" class="hover:underline me-4 md:me-6">Conditions générales</a>
                </li>
                <li>
                    <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" class="hover:underline me-4 md:me-6">Licence</a>
                </li>
                <li>
                    <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ" class="hover:underline">Contact</a>
                </li>
            </ul>
        </div>
        <hr class="my-2  border-gray-200 sm:mx-auto lg:my-3" />
        <span class="block text-sm text-gray-500 text-center ">© 2023 <a href="https://flowbite.com/" class="hover:underline">KittyKat™</a>.  All Rights Reserved.</span>
    </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4 border-b">
  <a href="/" class="flex items-center space-x-3 rtl:space-x-reverse">
      <span class="sr-only">Your Company</span>
      <%= image_tag("logo_kitty2.png", class: "h-11 w-auto", alt: "This is the logo of our Kitty Kat company")%>
  </a>
  <div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
      <button type="button" class="flex text-sm rounded-full md:me-0 focus:ring-4 focus:ring-gray-300" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
        <span class="sr-only">Open user menu</span>
        <%= image_tag("user_connexion_picto.png", class: "w-10 h-10 rounded-full", alt: "user photo")%>
      </button>
      <!-- Dropdown menu -->
      <div class="z-50 bg-white hidden my-4 text-base list-none divide-y divide-gray-200 rounded-lg shadow" id="user-dropdown">
        <% if user_signed_in? %>
          <div class="px-4 py-3">
            <span class="block text-sm text-gray-500"><%= current_user.email %></span>
          </div>
          <ul class="py-2" aria-labelledby="user-menu-button">
            <li>
              <a href="/users/show" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-500 dark:hover:text-white">Mon Profil</a>
            </li>
            <li>
              <%= link_to "Mon Panier", cart_path(current_user), class:"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-500 dark:hover:text-white"%>
            </li>
            <li>
              <%= button_to "Se déconnecter", destroy_user_session_path, method: :delete, data: {turbo_method: :delete}, :class=>"block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-500 dark:hover:text-white" %>
            </li>
        <% else %>
            <li>
              <a href="/users/sign_in" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-500 dark:hover:text-white">Se connecter</a>
            </li>
            <li>
              <a href="/users/sign_up" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-500 dark:hover:text-white">S'inscrire</a>
            </li>
          </ul>
        <% end %>
      </div>

      <!-- Menu Navif-gation collapse -->
      <button data-collapse-toggle="navbar-user" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200" aria-controls="navbar-user" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
    </button>
  </div>
  <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-user">
    <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 bg-white rounded-lg  md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0">
      <li>
        <a href="/" class="text-sm font-semibold leading-6 text-gray-900" aria-current="page">Accueil</a>
      </li>
      <li>
        <a href="/items" class="text-sm font-semibold leading-6 text-gray-900">Notre Collection</a>
      </li>
      <li>
        <a href="/contact" class="text-sm font-semibold leading-6 text-gray-900">Contact</a>
      </li>
    </ul>
  </div>
  </div>
</nav>

app/views/layouts/_toast.html.erb
<div id="toast-bottom-right" class="fixed flex items-center w-full max-w-xs p-4 space-x-4 text-gray-500 bg-white divide-x rtl:divide-x-reverse divide-gray-200 rounded-lg shadow right-5 bottom-5 dark:text-gray-400 dark:divide-gray-700 space-x dark:bg-gray-800" role="alert">
    <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-blue-500 bg-blue-100 rounded-lg dark:bg-blue-800 dark:text-blue-200">
        <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 20">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.147 15.085a7.159 7.159 0 0 1-6.189 3.307A6.713 6.713 0 0 1 3.1 15.444c-2.679-4.513.287-8.737.888-9.548A4.373 4.373 0 0 0 5 1.608c1.287.953 6.445 3.218 5.537 10.5 1.5-1.122 2.706-3.01 2.853-6.14 1.433 1.049 3.993 5.395 1.757 9.117Z"/>
        </svg>
        <span class="sr-only">Fire icon</span>
    </div>
    <div class="ms-3 text-sm font-normal"><%= notice %></div>
    <button type="button" class="ms-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex items-center justify-center h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700" data-dismiss-target="#toast-default" aria-label="Close">
        <span class="sr-only">Close</span>
        <svg class="w-3 h-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
        </svg>
    </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KittyKat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- FLOWBITE MA GUEULE --> 
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.0/flowbite.min.css" rel="stylesheet" />

    <!-- librairie de stripe --> 
    <script src="https://js.stripe.com/v3/"></script>

    <!--CDN Tailwind-->
    <script src="https://cdn.tailwindcss.com"></script>
    <style type="text/tailwindcss">
      @layer utilities {
        .content-auto {
          content-visibility: auto;
        }
      }
    </style>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="min-h-screen">

    <!-- À l'avenir retirer absolute pour pas que navbar et reste se chevauche-->
    <header class="inset-x-0 top-0 z-50">
      <%= render 'layouts/navbar' %>
    </header>

    <%= yield %>

    <%= render 'layouts/footer' %>

    <% if notice != nil %>
      <%= render 'layouts/toast' %>
    <% end %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.0/flowbite.min.js"></script> <!-- FLOWBITE MA GUEULE --> 
  </body>
</html>